% load IVHs
load(Experiment.GetDataPath('VUMC'),"voImageVolumeHandlers")

% No shape and size
voFeatureNames = [...
                FirstOrderFeature.GetAllFeatures3D(),...
                GLCMFeature.GetAllFeatures3D(),...
                GLRLMFeature.GetAllFeatures3D()];

oAllFeatures = Feature.ExtractFeaturesForImageVolumeHandlers(...
    voImageVolumeHandlers,...
    voFeatureNames,...
    FeatureExtractionParameters('FeatureExtractionParameters.xlsx'),...
    "VUMC");
save([Experiment.GetResultsDirectory(), '\AllFeatures.mat'], "oAllFeatures")
